name: filiphnet2017
description: Filip Hracek's homepage + associated tooling.
version: 0.0.1

environment:
  sdk: '>=1.23.0 <2.0.0'

dev_dependencies:
  args: ^0.13.7
  html: ^0.13.2
  markdown: ^0.11.3
